Set Django user password to unusable.
Karaage sets the Django user password to the LDAP encrypted value, which
is then used to fill the LDAP field. This needs to be reset to something
Django supports, or Django will crash if the LDAP password check fails.

Error is:

File "/usr/lib/pymodules/python2.6/django/contrib/auth/backends.py",
line 17, in authenticate
    if user.check_password(password):

  File "/usr/lib/pymodules/python2.6/django/contrib/auth/models.py",
line 261, in check_password
    return check_password(raw_password, self.password)

  File "/usr/lib/pymodules/python2.6/django/contrib/auth/models.py",
line 40, in check_password
    algo, salt, hsh = enc_password.split('$')

ValueError: too many values to unpack